In [108]:
import numpy as np

In [109]:
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def sigmoid_deriv(z):
    s = sigmoid(z)
    return s * (1 - s) 


In [110]:
x = np.array([[1],[0.5]]) #input data
y = 3.97 #actual label
learning_rate = 0.5

#weights and biases initation
W1 = np.array([[1, 0], [-1, 0]], dtype=float)
b1 = np.array([[0], [0.5]])

W2 = np.array([[0, -2, -1], [1, 1, 1]], dtype=float)
b2 = np.zeros((3, 1))

W3 = np.array([[1], [-1], [1]], dtype=float)
b3 = np.array([[2.0]])

In [111]:
#forward propagation
z1 = W1.T @ x + b1    # first hiden layer
a1 = sigmoid(z1)
a1


array([[0.62245933],
       [0.62245933]])

In [112]:
z2 = W2.T @ a1 + b2   #second hiden layar 
a2 = sigmoid(z2)
a2


array([[0.65077768],
       [0.34922232],
       [0.5       ]])

In [113]:
z3 = W3.T @ a2 + b3 #output layar
y_hat = z3  
y_hat

array([[2.80155536]])

In [114]:
# weights = [W1, W2, W3]
# biases  = [b1, b2, b3]

# # forward propagation
# activations = [x] 

# for i, (W, b) in enumerate(zip(weights, biases)):
#     z = W.T @ activations[-1] + b
    
#     if i < len(weights) - 1:   
#         a = sigmoid(z)
#     else:                       
#         a = z
    
#     activations.append(a)

# y_hat = activations[-1]

In [115]:
loss = 0.5 * (y - y_hat[0,0])**2    #MSE loss function
print(f"y_hat = {y_hat[0,0]:.4f}")
print(f"Loss  = {loss:.4f}\n")

y_hat = 2.8016
Loss  = 0.6826



In [116]:
#back propagation
#level one: Gradient to loss function
"""
L = 0.5*(y - y_hat)^2  =>  dL/dy_hat = -(y - y_hat)
"""
delta3 = -(y - y_hat)
print(f"delta3 = {delta3[0,0]:.4f}")



delta3 = -1.1684


In [117]:
#level two: Gradient to W3 and b3
"""
z3 = W3.T @ a2 + b3
dL/d(W3.T) = delta3 @ a2.T   shape: (1,1)@(1,3) = (1,3)
dL/dW3 = (dL/d(W3.T)).T      shape: (3,1)
"""
dW3 = (delta3 @ a2.T).T                        # (3,1)
db3 = delta3                                    # (1,1)
print(f"\ndW3 =\n{dW3}")
print(f"db3 = {db3[0,0]:.4f}")


dW3 =
[[-0.76039769]
 [-0.40804695]
 [-0.58422232]]
db3 = -1.1684


In [118]:
#level three: Gradient to sigmoid then to W2 and b2
"""
dL/da2 = W3.T @ delta3 notice that (W3.T @ a2).T = a2.T @ W3 ...
... (A@B).T = B.T@A.T  =>  dL/da2 = W3 @ delta3
dL/dz2 = dL/da2 * sigmoid'(z2)
z2 = W2.T @ a1 + b2
dL/dW2 = (delta2 @ a1).T
delta2 = dL/da2 * sigmoid'(z2)
"""
da2 = W3 @ delta3
delta2 = da2 * sigmoid_deriv(z2)              
print(f"\ndelta2 =\n{delta2}")


delta2 =
[[-0.26554785]
 [ 0.26554785]
 [-0.29211116]]


In [119]:
dW2 = (delta2 @ a1.T).T
db2 = delta2
print(f"\ndW2 =\n{dW2}")
print(f"db2 =\n{db2}")


dW2 =
[[-0.16529274  0.16529274 -0.18182732]
 [-0.16529274  0.16529274 -0.18182732]]
db2 =
[[-0.26554785]
 [ 0.26554785]
 [-0.29211116]]


In [120]:
#level four: Gradient to sigmoid then to W1 and b1
da1 = W2 @ delta2
delta1 = da1 * sigmoid_deriv(z1)
print(f"\ndelta1 =\n{delta1}")



delta1 =
[[-0.05616225]
 [-0.06864721]]


In [121]:

dW1 = (delta1 @ x.T).T
db1 = delta1
print(f"\ndW1 =\n{dW1}")
print(f"db1 =\n{db1}")


dW1 =
[[-0.05616225 -0.06864721]
 [-0.02808113 -0.0343236 ]]
db1 =
[[-0.05616225]
 [-0.06864721]]


In [122]:
#updating weights
params = {
    'W1': (W1, dW1), 'b1': (b1, db1),
    'W2': (W2, dW2), 'b2': (b2, db2),
    'W3': (W3, dW3), 'b3': (b3, db3),
}

for name, (param, grad) in params.items():
    param -= learning_rate * grad
    print(f"{name} =\n{param}\n")
    #print(f"{name}shape =\n{param.shape}\n")


W1 =
[[ 1.02808113  0.0343236 ]
 [-0.98595944  0.0171618 ]]

b1 =
[[0.02808113]
 [0.5343236 ]]

W2 =
[[ 0.08264637 -2.08264637 -0.90908634]
 [ 1.08264637  0.91735363  1.09091366]]

b2 =
[[ 0.13277392]
 [-0.13277392]
 [ 0.14605558]]

W3 =
[[ 1.38019885]
 [-0.79597652]
 [ 1.29211116]]

b3 =
[[2.58422232]]

